### PR TITLE
Made the 180 rotation optional

### PR DESCRIPTION
**Pull request by SoylentGraham**
I needed the same as #1, for the image to be the right way up :)

### CODE REVIEW

**Comment by motionsmith** [comment]
@SoylentGraham Thanks for the pull request. I think while we're allowing the user to control the rotation, we might as well give them all 4 options, what do you think? We could  allow them to rotate 90 degrees CW, CCW, and 180 degrees (or leave it at 0).

I also appreciate that you updated the dummy project. Nice thorough work! We're grateful for your contribution.

**Comment by SoylentGraham** [comment]
I did think of changing it to an angle... and a getter/setter for enable like I did with opacity/stabilisation.
It's not even strictly a flip.... 180 is not the same as a Y-bottom texture sample flip, if that's what it was for?
What was the motivation in rotating it 180 degrees in the first place?

**Comment by SoylentGraham** [comment]
Oh, also, I would have removed having 2 different `CameraParams` classes, when you kinda want them exactly the same. (they're just dumb data classes) No need to throw an exception.

But this was a rushed job, so maybe there's a project-orientated reason to have two separate files I didn't see :)

**Comment by motionsmith** [comment]
Ultumately I kept the rotation as a boolean because `0` and `180` were the only values that did anything in-between values <180 produced the same result as inputting `0`.

I agree, it would be nice to consolidate the two params classes. And yeah, I'm not too serious about throwing exceptions in the dummy project, it was just the convention I started with earlier. But I didn't 'want to give people the idea that the dummy class ever actually does anything. :)

I appreciate your pull request, even if it is rushed. It gives me an excuse to make a few upgrades to the project!

**Pull request merged**
